/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_androidex_MainActivity */

#ifndef _Included_com_example_androidex_MainActivity
#define _Included_com_example_androidex_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_androidex_MainActivity
 * Method:    driverOpen
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_androidex_MainActivity_driverOpen
  (JNIEnv *, jobject);

/*
 * Class:     com_example_androidex_MainActivity
 * Method:    driverClose
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_example_androidex_MainActivity_driverClose
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_example_androidex_MainActivity
 * Method:    moveUp
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_example_androidex_MainActivity_moveUp
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_example_androidex_MainActivity
 * Method:    moveDown
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_example_androidex_MainActivity_moveDown
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_example_androidex_MainActivity
 * Method:    moveLeft
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_example_androidex_MainActivity_moveLeft
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_example_androidex_MainActivity
 * Method:    moveRight
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_example_androidex_MainActivity_moveRight
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_example_androidex_MainActivity
 * Method:    checkEnding
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_example_androidex_MainActivity_checkEnding
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
